// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcr2Del9hYBXkWpTmWU9hTasrBbDFBVGs',
    appId: '1:696172708564:web:6a1ba82beb79d31f997141',
    messagingSenderId: '696172708564',
    projectId: 'booknow-app-bkikenski',
    authDomain: 'booknow-app-bkikenski.firebaseapp.com',
    storageBucket: 'booknow-app-bkikenski.appspot.com',
    measurementId: 'G-9GZNM2QS2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zsHbaieDh7R7vfPSX8uQvI1KB7QyZug',
    appId: '1:696172708564:android:ef1d13a871bed776997141',
    messagingSenderId: '696172708564',
    projectId: 'booknow-app-bkikenski',
    storageBucket: 'booknow-app-bkikenski.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhm_bsHSdj1RqTAOOzPs-LucpQfs6FAhs',
    appId: '1:696172708564:ios:c62957dfadfea643997141',
    messagingSenderId: '696172708564',
    projectId: 'booknow-app-bkikenski',
    storageBucket: 'booknow-app-bkikenski.appspot.com',
    iosBundleId: 'com.boriskikenski.bookNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhm_bsHSdj1RqTAOOzPs-LucpQfs6FAhs',
    appId: '1:696172708564:ios:2546712a2aa7a98f997141',
    messagingSenderId: '696172708564',
    projectId: 'booknow-app-bkikenski',
    storageBucket: 'booknow-app-bkikenski.appspot.com',
    iosBundleId: 'com.boriskikenski.bookNow.RunnerTests',
  );
}
